#!/usr/bin/env python3
"""
OWUI-Cursor Bridge: Watcher Script
Monitors for instructions from OWUI and formats them for Cursor.

Run this in your WSL terminal:
    python3 ~/projects/owui-cursor-bridge/cursor/watcher.py
"""

import json
import time
from pathlib import Path
from datetime import datetime
from collections import deque

# === CONFIGURATION ===
# All paths use the shared bridge folder
BRIDGE_PATH = Path("/mnt/f/AI/owui-bridge")
INSTRUCTIONS_PATH = BRIDGE_PATH / "instructions"
LOGS_PATH = BRIDGE_PATH / "logs"

# Cursor instruction file - IN the bridge folder, not ~/projects/
INSTRUCTION_FILE = BRIDGE_PATH / "CURSOR_INSTRUCTION.md"

# How many past instructions to keep in history
HISTORY_SIZE = 5

# How often to check for new instructions (seconds)
POLL_INTERVAL = 1.0

# === STATE ===
instruction_history = deque(maxlen=HISTORY_SIZE)


def setup():
    """Ensure all required directories exist."""
    INSTRUCTIONS_PATH.mkdir(parents=True, exist_ok=True)
    LOGS_PATH.mkdir(parents=True, exist_ok=True)
    log(f"Bridge path: {BRIDGE_PATH}")
    log(f"Instructions will appear at: {INSTRUCTION_FILE}")


def log(message: str):
    """Print timestamped log message."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{timestamp}] {message}")


def write_instruction_file(instruction: str, instruction_id: str):
    """
    Write the instruction to CURSOR_INSTRUCTION.md
    Overwrites main content but preserves history section.
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    # Add to history
    instruction_history.append({
        "id": instruction_id[:8],
        "time": timestamp,
        "preview": instruction[:50] + "..." if len(instruction) > 50 else instruction
    })
    
    # Build the instruction file
    content = f"""# 🎯 Cursor Instruction

**From:** OWUI Planning Session  
**Time:** {timestamp}  
**ID:** `{instruction_id[:8]}`

---

## Instruction

{instruction}

---

## How to Use

1. Select all the text in the "Instruction" section above
2. Open Cursor's AI chat (Cmd/Ctrl + L)
3. Paste and send

---

## Recent History

| Time | ID | Preview |
|------|-----|---------|
"""
    
    # Add history rows (most recent first)
    for item in reversed(instruction_history):
        content += f"| {item['time']} | `{item['id']}` | {item['preview']} |\n"
    
    content += "\n---\n*Generated by owui-cursor-bridge*\n"
    
    # Write the file
    INSTRUCTION_FILE.write_text(content, encoding="utf-8")
    log(f"✓ Instruction written to: {INSTRUCTION_FILE}")
    log(f"  └─ \"{instruction[:60]}{'...' if len(instruction) > 60 else ''}\"")


def process_instruction(filepath: Path):
    """Process a single instruction file."""
    try:
        data = json.loads(filepath.read_text(encoding="utf-8"))
        instruction_id = data.get("id", "unknown")
        action = data.get("action", "unknown")
        
        log(f"Processing: {filepath.name} (action: {action})")
        
        if action == "instruct":
            # New instruction format - extract and write to file
            payload = data.get("payload", {})
            instruction = payload.get("instruction", "")
            
            if instruction:
                write_instruction_file(instruction, instruction_id)
            else:
                log(f"⚠ Empty instruction in {filepath.name}")
        
        elif action == "create_file":
            # Legacy format - still support it
            payload = data.get("payload", {})
            file_path = payload.get("path", "")
            content = payload.get("content", "")
            
            if file_path and content:
                # Convert to instruction format
                instruction = f"Create a file at `{file_path}` with the following content:\n\n```\n{content}\n```"
                write_instruction_file(instruction, instruction_id)
            else:
                log(f"⚠ Invalid create_file payload in {filepath.name}")
        
        else:
            log(f"⚠ Unknown action '{action}' in {filepath.name}")
        
        # Clean up processed instruction
        filepath.unlink()
        log(f"Cleaned up: {filepath.name}")
        
    except json.JSONDecodeError as e:
        log(f"✗ Invalid JSON in {filepath.name}: {e}")
    except Exception as e:
        log(f"✗ Error processing {filepath.name}: {e}")


def watch():
    """Main watch loop."""
    log("Watcher started. Waiting for instructions...")
    log(f"Watching: {INSTRUCTIONS_PATH}")
    log("")
    
    while True:
        try:
            # Find all .json files in instructions folder
            instruction_files = sorted(INSTRUCTIONS_PATH.glob("*.json"))
            
            for filepath in instruction_files:
                process_instruction(filepath)
            
            time.sleep(POLL_INTERVAL)
            
        except KeyboardInterrupt:
            log("\nWatcher stopped by user.")
            break
        except Exception as e:
            log(f"✗ Unexpected error: {e}")
            time.sleep(POLL_INTERVAL)


if __name__ == "__main__":
    print("=" * 50)
    print("OWUI-Cursor Bridge Watcher v0.2")
    print("=" * 50)
    setup()
    print("")
    watch()